nff/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name="nff"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tentang/$', views.about, name='about'),
    url(r'^registrasi/$', views.register, name='registration'),
    url(r'^konfirmasi/$', views.Confirm.as_view(), name='confirmation'),
    url(r'^unggah_formulir/$', views.Form.as_view(), name='form_upload'),
    url(r'^success/$', views.success, name='success'),
    url(r'^formulir/$', views.application, name='application'),
    url(r'^home/$', views.index, name='home'),
    url(r'^kompetisi/$', views.competition, name='competition'),
    url(r'^galeri_tari/$', views.gallery_tari, name='gallery_tari'),
    url(r'^galeri_padus/$', views.gallery_padus, name='gallery_padus'),
    url(r'^poster/$', views.poster, name='poster'),
]

nff_main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('nff.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from gdstorage.storage import GoogleDriveStorage
import os
from django.db.models import Q

# Create your models here.
gd_storage = GoogleDriveStorage()
def bukti_bayar_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.nama_tim, 'bukti_bayar', ext)
    return os.path.join('bukti_bayar', filename)

def forms_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.nama_tim, 'forms', ext)
    return os.path.join('forms', filename)

class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    category_type = models.CharField(max_length=31)

    def __str__(self):
        return self.category_type

class Registration(models.Model):
    nama_tim = models.CharField(max_length=30, unique=True)
    asal_tim = models.CharField(max_length=30)
    kategori = models.ForeignKey(Category, on_delete=models.CASCADE, limit_choices_to=Q(id=1) | Q(id=2))
    nama_contact_person = models.CharField(max_length=30)
    nomor_contact_person = models.CharField(max_length=30)
    email_contact_person = models.EmailField(max_length=50, unique=True)

    def get_absolute_url(self):
        return reverse('nff:index')

    def __str__(self):
        return self.nama_tim

class Confirmation(models.Model):
    from django.utils import timezone
    nama_tim = models.ForeignKey(Registration, to_field='nama_tim')
    kategori = models.ForeignKey(Category, on_delete=models.CASCADE)
    nama_rekening_pengirim = models.CharField(max_length=30)
    tanggal_transfer = models.DateField(default=timezone.now())
    bukti = models.ImageField(upload_to=bukti_bayar_file_name)

    def __str__(self):
        return '%s' % (self.nama_tim)

    def asal(self):
        return 'Asal {:10}'.format(self.nama_tim.asal_tim)

    def contoh(self):
        return os.path.basename(self.bukti.name)

    @property
    def filename(self):
       return os.path.basename(self.bukti.name)

class Form_upload(models.Model):
    nama_tim = models.ForeignKey(Registration, to_field='nama_tim')
    form = models.FileField(upload_to=forms_file_name)

    def __str__(self):
        return str(self.nama_tim)

nff/forms.py
from django import forms
from .models import Confirmation, Form_upload, Registration

class ConfirmForm(forms.ModelForm):

    class Meta:
        model = Confirmation
        fields = ['nama_tim', 'kategori', 'nama_rekening_pengirim', 'tanggal_transfer', 'bukti']
        widgets = {
            'nama_tim': forms.TextInput(),
            'tanggal_transfer': forms.SelectDateWidget()
        }
        error_messages = {
            'nama_tim':{
                'invalid_choice': "We don't have that team name registered. Please check again, the name is case sensitive",
                }
            }

class UploadForm(forms.ModelForm):

    class Meta:
        model = Form_upload
        fields = ['nama_tim', 'form']
        widgets = {
            'nama_tim': forms.TextInput()
        }
        error_messages = {
            'nama_tim':{
                'invalid_choice': "We don't have that team name registered. Please check again, the name is case sensitive",
                }
            }


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = ['nama_tim','asal_tim', 'kategori', 'nama_contact_person','nomor_contact_person', 'email_contact_person']

nff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views import generic
from django.http import Http404
from .forms import ConfirmForm, UploadForm, RegisterForm
from django.core.mail import send_mail
from django.template.loader import get_template
from .models import Registration

# Create your views here.
def index(request):
    return render(request, 'nff/index.html')

def about(request):
    return render(request, 'nff/about.html')

def competition(request):
    return render(request, 'nff/competition.html')

def success(request):
    return render(request, 'nff/success-padus.html')

def application(request):
    return render(request, 'nff/application_form.html')

def gallery_tari(request):
    return render(request, 'nff/gallery-tari.html')

def gallery_padus(request):
    return render(request, 'nff/gallery-padus.html')

def poster(request):
    return render(request, 'nff/poster.html')

def register(request):
    return render(request, 'nff/register-closed.html')


class Register(generic.View):
    form_class = RegisterForm
    template_name = 'nff/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            validform = form.save(commit=False)

            #normalized data
            email_contact_person = form.cleaned_data['email_contact_person']
            kategori = form.cleaned_data['kategori']
            if "Padus" in str(kategori):
                send_mail(
                    'Terima kasih telah mendaftar NFF!',
                    '''
                    Terima kasih sudah mendaftar dalam kompetisi Paduan Suara The 12th NFF.
                    Untuk pembayaran, dapat transfer ke rekening:
                    BNI a/n Klara Amanda Aninditya
                    0585465368

                    Dengan jumlah:
                    Kategori A - Rp400.000
                    Kategori B - Rp450.000

                    Ketika sudah melakukan pembayaran dan melakukan konfirmasi pada kami, tim anda secara resmi sudah menjadi peserta The 12th NFF.

                    Kami tunggu pembayarannya karena kuota terbatas.

                    Terima kasih.
                     ''',
                    'admin@the12thnff.com',
                    [email_contact_person],
                    fail_silently=False,
                    html_message=
                    '''
                    <html>
                    <head>
                    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
                    </head>
                    <body>
                    <div style="text-align:center;">
                    <div class="image-container">
                        <img style="width: 7em;" src="https://the12thnff.com/static/nff/images/icon.png">
                    </div>
                    <h1 style="color: #d5b135;">Terima kasih sudah mendaftar dalam kompetisi Paduan Suara The 12th NFF.</h1>
                    <p>Untuk pembayaran, dapat transfer ke rekening:<br />
                    BNI a/n Klara Amanda Aninditya<br />
                    0585465368<br /><br />

                    Dengan jumlah:<br />
                    Kategori A - Rp400.000<br />
                    Kategori B - Rp450.000<br /><br />

                    Ketika sudah melakukan pembayaran dan melakukan konfirmasi pada kami, tim anda secara resmi sudah menjadi peserta The 12th NFF.<br /><br />

                    Kami tunggu pembayarannya karena kuota terbatas.<br /><br />

                    Terima kasih.</p>
                    </div>
                    </body>
                    </html>
                     '''
                )
                validform.save()
                return render(request, 'nff/success-padus.html')
            else:
                send_mail(
                    'Terima kasih telah mendaftar NFF!',
                    '''
                    Terima kasih sudah mendaftar dalam kompetisi Tari Tradisional The 12th NFF.
                    Untuk pembayaran, dapat transfer ke rekening:
                    BNI a/n Klara Amanda Aninditya
                    0585465368

                    Dengan jumlah:
                    Kategori A - Rp300.000
                    Kategori B - Rp325.000
                    Kategori C - Rp350.000

                    Ketika sudah melakukan pembayaran dan melakukan konfirmasi pada kami, tim anda secara resmi sudah menjadi peserta The 12th NFF.

                    Kami tunggu pembayarannya karena kuota terbatas.

                    Terima kasih.
                     ''',
                    'admin@the12thnff.com',
                    [email_contact_person],
                    fail_silently=False,
                    html_message=
                    '''
                    <html>
                    <head>
                    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
                    </head>
                    <body>
                    <div style="text-align:center;">
                    <div class="image-container">
                        <img style="width: 7em;" src="https://the12thnff.com/static/nff/images/icon.png">
                    </div>
                    <h1 style="color: #d5b135;">Terima kasih sudah mendaftar dalam kompetisi Tari Tradisional The 12th NFF.</h1>
                    <p>Untuk pembayaran, dapat transfer ke rekening:<br />
                    BNI a/n Klara Amanda Aninditya<br />
                    0585465368<br /><br />

                    Dengan jumlah:<br />
                    Kategori A - Rp300.000<br />
                    Kategori B - Rp325.000<br />
                    Kategori C - Rp350.000<br /><br />

                    Ketika sudah melakukan pembayaran dan melakukan konfirmasi pada kami, tim anda secara resmi sudah menjadi peserta The 12th NFF.<br /><br />

                    Kami tunggu pembayarannya karena kuota terbatas.<br /><br />

                    Terima kasih.</p>
                    </div>
                    </body>
                    </html>
                     '''
                )
                validform.save()
                return render(request, 'nff/success-tari.html')

        return render(request, self.template_name, {'form':form})


class Confirm(generic.View):
    form_class = ConfirmForm
    template_name = 'nff/confirmation_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            validform = form.save(commit=False)

            #normalized data
            nama_tim = form.cleaned_data['nama_tim']
            tim = Registration.objects.get(nama_tim=nama_tim)
            email_contact_person = tim.email_contact_person
            kategori = form.cleaned_data['kategori']
            if "Padus" in str(kategori):
                send_mail(
                    'Terima kasih telah melakukan pembayaran',
                    '''
                    Terima kasih sudah melakukan pembayaran.

                    Selamat! Anda telah resmi bergabung dalam The 12th NFF.
                    Untuk selanjutnya, silakan download dan isi application form.
                    Batas upload form sampai dengan tanggal 8 Januari 2018.
                    Terima kasih.

                    https://the12thnff.com/static/nff/download/APPLICATION%20FORM%20PADUS.docx
                     ''',
                    'admin@the12thnff.com',
                    [email_contact_person],
                    fail_silently=False,
                    html_message=
                    '''
                    <html>
                    <head>
                    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
                    </head>
                    <body>
                    <div style="text-align:center;">
                    <div class="image-container">
                        <img style="width: 7em;" src="https://the12thnff.com/static/nff/images/icon.png">
                    </div>
                    <h1 style="color: #d5b135;">Terima kasih sudah melakukan pembayaran.</h1>
                    <p>
                      Selamat! Anda telah resmi bergabung dalam The 12th NFF.<br /><br />
                      Untuk selanjutnya, silakan download dan isi application form.<br /><br />
                      Batas upload form sampai dengan tanggal 8 Januari 2018.<br /><br />
                      Terima kasih.
                    </p>
                    <a href="https://the12thnff.com/static/nff/download/APPLICATION%20FORM%20PADUS.docx" download="12th NFF - APPLICATION FORM PADUS.docx">12th NFF - APPLICATION FORM PADUS</a><br />
                    </div>
                    </body>
                    </html>
                     '''
                )
                validform.save()
                return render(request, 'nff/success-confirm-padus.html')
            else:
                send_mail(
                    'Terima kasih telah melakukan pembayaran',
                    '''

nff/templates/nff/about.html
{% extends 'nff/base.html' %}
{% block title %}
About NFF
{% endblock %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{%static 'nff/css/about.css' %}" />
<link rel="stylesheet" href="{%static 'nff/css/jquery.pagepiling.css' %}" />
{% endblock %}
{% block content %}
<div id="pagepiling">
    <div class="section" id="section1">
      <div id="myNav4" class="overlay">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav4()">&times;</a>
        <div class="overlay-content">
          <a href={% url 'nff:index' %}>NFF</a>
          <a href={% url 'nff:about' %}>Tentang</a>
          <a href={% url 'nff:competition' %}>Kompetisi</a>
          <a href={% url 'nff:registration' %}>Registrasi</a>
          <a href={% url 'nff:confirmation' %}>Konfirmasi</a>
          <a href={% url 'nff:form_upload' %}>Unggah Formulir</a>
          <a href={% url 'nff:application' %}>Formulir Aplikasi</a>
        </div>
      </div>
      <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
        <div class="navbar-right" id="navbarTogglerDemo02">
          <a class="navbar-brand" href="{% url 'nff:index' %}">{% if request.get_full_path == "/about/" %}<img class="nff-icon" src="{%static 'nff/images/icon-white.png' %}" alt="logo" />{% else %}<img class="nff-icon" src="{%static 'nff/images/icon.png' %}" alt="logo" />{% endif %}</a>
          <ul class="nav navbar-nav ml-auto">
            <span class="menu" onclick="openNav4()"><i class="fa fa-bars" aria-hidden="true"></i></span>
          </ul>
        </div>
      </nav>
    	<h1>TENTANG KAMI</h1>
    </div>
    
    <div class="section" id="section2">
    	<div class="intro">
        <div id="myNav1" class="overlay">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav1()">&times;</a>
          <div class="overlay-content">
            <a href={% url 'nff:index' %}>NFF</a>
            <a href={% url 'nff:about' %}>Tentang</a>
            <a href={% url 'nff:competition' %}>Kompetisi</a>
            <a href={% url 'nff:registration' %}>Registrasi</a>
            <a href={% url 'nff:confirmation' %}>Konfirmasi</a>
            <a href={% url 'nff:form_upload' %}>Unggah Formulir</a>
            <a href={% url 'nff:application' %}>Formulir Aplikasi</a>
          </div>
        </div>
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
          <div class="navbar-right" id="navbarTogglerDemo02">
            <a class="navbar-brand" href="{% url 'nff:index' %}">{% if request.get_full_path == "/about/" %}<img class="nff-icon" src="{%static 'nff/images/icon-white.png' %}" alt="logo" />{% else %}<img class="nff-icon" src="{%static 'nff/images/icon.png' %}" alt="logo" />{% endif %}</a>
            <ul class="nav navbar-nav ml-auto">
              <span class="menu" onclick="openNav1()"><i class="fa fa-bars" aria-hidden="true"></i></span>
            </ul>
          </div>
        </nav>
    		<h6>Tentang NFF</h6>
        <div class="container">
          <p>National Folklore Festival (NFF) adalah acara tahunan bertemakan budaya Indonesia terbesar yang diselenggarakan oleh mahasiswa Fakultas Ekonomi dan Bisnis Universitas Indonesia. Di bawah naungan Departemen Apresiasi Seni dan Budaya dari Badan Eksekutif Mahasiswa (BEM), National Folklore Festival berkontribusi aktif setiap tahunnya melestarikan dan menjaga persatuan dalam kebergaman budaya Indonesia.<br /><br />

          Pada tahun ini, kami dengan bangga mempersembahkan The 12th National Folklore Festival “Sekarnaka Sandya”, yang akan diselenggarakan pada akhir bulan Februari hingga awal bulan Maret 2018. The 12th National Folklore Festival terdiri atas rangkaian main event berupa perlombaan paduan suara dan tari tradisional berskala nasional, untuk tingkat SMA, Universitas, dan Umum. The 12th NFF juga memiliki rangkaian pre-event berupa perlombaan tradisional dan mini museum, untuk meningkatkan awareness terhadap budaya Indonesia dalam lingkup Fakultas Ekonomi dan Bisnis Universitas Indonesia serta</p>
        </div>
    	</div>
    </div>
    <div class="section" id="section3">
    	<div class="intro">
        <div id="myNav2" class="overlay">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav2()">&times;</a>
          <div class="overlay-content">
            <a href={% url 'nff:index' %}>NFF</a>
            <a href={% url 'nff:about' %}>Tentang</a>
            <a href={% url 'nff:competition' %}>Kompetisi</a>
            <a href={% url 'nff:registration' %}>Registrasi</a>
            <a href={% url 'nff:confirmation' %}>Konfirmasi</a>
            <a href={% url 'nff:form_upload' %}>Unggah Formulir</a>
            <a href={% url 'nff:application' %}>Formulir Aplikasi</a>
          </div>
        </div>
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
          <div class="navbar-right" id="navbarTogglerDemo02">
            <a class="navbar-brand" href="{% url 'nff:index' %}">{% if request.get_full_path == "/about/" %}<img class="nff-icon" src="{%static 'nff/images/icon-white.png' %}" alt="logo" />{% else %}<img class="nff-icon" src="{%static 'nff/images/icon.png' %}" alt="logo" />{% endif %}</a>
            <ul class="nav navbar-nav ml-auto">
              <span class="menu" onclick="openNav2()"><i class="fa fa-bars" aria-hidden="true"></i></span>
            </ul>
          </div>
        </nav>
    		<h6>Sekarnaka Sandya</h6>
        <div class="container">
          <p>Tema “Sekarnaka Sandya” memiliki arti bunga emas persatuan. Bunga memiliki kesamaan filosofis dengan kebudayaan yang dimiliki oleh bangsa Indonesia, sedangkan emas melambangkan bahwa keberagaman budaya nusantara merupakan harta yang sangat berharga dan aset bangsa Indonesia sendiri, yang diharapkan mampu mempererat rasa persatuan bangsa Indonesia. Bentuk kebudayaan itu sendiri salah satunya berupa pertunjukan seni budaya, yang diwujudkan dalam kompetisi Paduan Suara dan Tari Tradisional di National Folklore Festival. The 12th National Folklore Festival merupakan wadah bagi para generasi muda untuk melakukan aksi nyata melestarikan keberagaman budaya sebagai bagian dari harta bangsa Indonesia.</p>
        </div>
    	</div>
    </div>
    <div class="section" id="section4">
      <div id="myNav3" class="overlay">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav3()">&times;</a>
        <div class="overlay-content">
          <a href={% url 'nff:index' %}>NFF</a>
          <a href={% url 'nff:about' %}>Tentang</a>
          <a href={% url 'nff:competition' %}>Kompetisi</a>
          <a href={% url 'nff:registration' %}>Registrasi</a>
          <a href={% url 'nff:confirmation' %}>Konfirmasi</a>
          <a href={% url 'nff:form_upload' %}>Unggah Formulir</a>
          <a href={% url 'nff:application' %}>Formulir Aplikasi</a>
        </div>
      </div>
      <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
        <div class="navbar-right" id="navbarTogglerDemo02">
          <a class="navbar-brand" href="{% url 'nff:index' %}">{% if request.get_full_path == "/about/" %}<img class="nff-icon" src="{%static 'nff/images/icon-white.png' %}" alt="logo" />{% else %}<img class="nff-icon" src="{%static 'nff/images/icon.png' %}" alt="logo" />{% endif %}</a>
          <ul class="nav navbar-nav ml-auto">
            <span class="menu" onclick="openNav3()"><i class="fa fa-bars" aria-hidden="true"></i></span>
          </ul>
        </div>
      </nav>
      <h1>KELUARGA NFF</h1>
          <!--<img class="people" src="{%static 'nff/images/people/people-min.JPG' %}" alt="NFF Team" />-->
          <!--<div class="row">
            <div class="col-md-4 photo1">
              <img class="people-photo" src="{%static 'nff/images/people/mahendra.png' %}" alt="Mahendra" />
              <div class="photo-overlay photo1">
                <div class="overlay-text">
                  <p>Hunarko Mahendra<br />Project Officer</p>
                </div>
              </div>
            </div>
            <div class="col-md-4 photo2">
              <img class="people-photo" src="{%static 'nff/images/people/thania.png' %}" alt="Thania" />
              <div class="photo-overlay photo2">
                <div class="overlay-text">
                  <p>Thania Hanifa<br />Vice Project Officer</p>
                </div>
              </div>
            </div>
            <div class="col-md-4 photo3">
              <img class="people-photo" src="{%static 'nff/images/people/oliv.png' %}" alt="Oliv" />
              <div class="photo-overlay photo3">
                <div class="overlay-text">
                  <p>Olivia Gracia<br />VP, Marketing</p>
                </div>
              </div>
            </div>
          </div>
          <!--<button type="button" class="btn btn-outline-warning about-buttons">See all people</button>-->
    	</div>
    </div>
    <!--<div class="section" id="section4">
    	<div class="intro">
        <div id="myNav2" class="overlay">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav2()">&times;</a>
          <div class="overlay-content">
            <a href="/">Register</a>
            <a href="/confirmation">Comfirmation</a>
            <a href="/form">Form upload</a>
            <a href="/application">Application document</a>
          </div>
        </div>
        <nav class="navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
          <div class="navbar-right" id="navbarTogglerDemo02">
            <a class="navbar-brand" href="{% url 'nff:index' %}">{% if request.get_full_path == "/about/" %}<img class="nff-icon" src="{%static 'nff/images/icon-white.png' %}" alt="logo" />{% else %}<img class="nff-icon" src="{%static 'nff/images/icon.png' %}" alt="logo" />{% endif %}</a>
            <ul class="nav navbar-nav ml-auto">
              <span class="menu" onclick="openNav2()"><i class="fa fa-bars" aria-hidden="true"></i></span>
            </ul>
          </div>
        </nav>
    		<h6>Contact</h6>
        <!--<div class="row icon">
          <div class="col-md-4">
            <i class="fa fa-map-pin" aria-hidden="true"></i>
          </div>
          <div class="col-md-4">
            <i class="fa fa-mobile" aria-hidden="true"></i>
          </div>
          <div class="col-md-4">
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
          </div>
        </div>
        <div class="row text">
          <div class="col-md-4">
            <p>
            <b>Sekretariat BEM FEB UI</b><br />
              Student Center Lt.1 Kampus FEB UI<br />
              JL. Dr. Sumitro Djojohadikusumo (Lkr. Kampus Raya)<br />
              Depok, Jawa Barat 16424<br />
            </p>
          </div>
          <div class="col-md-4">
            <p>+62-xxxx-xxxx-xxxx</p>
          </div>
          <div class="col-md-4">
            <p>info@the12thnff.com</p>
          </div>
        </div>--
    	</div>
      {% include "nff/footer.html" %}
    </div>
</div>-->
{% endblock %}

{% block script %}
<script type="text/javascript" src="{%static 'nff/js/jquery.pagepiling.min.js' %}"></script>
<script>
function openNav4() {
    document.getElementById("myNav4").style.height = "100%";
}
function closeNav4() {
    document.getElementById("myNav4").style.height = "0%";
}
function openNav1() {
    document.getElementById("myNav1").style.height = "100%";
}
function closeNav1() {
    document.getElementById("myNav1").style.height = "0%";
}
function openNav2() {
    document.getElementById("myNav2").style.height = "100%";
}
function closeNav2() {
    document.getElementById("myNav2").style.height = "0%";
}
function openNav3() {
    document.getElementById("myNav3").style.height = "100%";
}
function closeNav3() {
    document.getElementById("myNav3").style.height = "0%";
}
</script>
<script type="text/javascript">
  var deleteLog = false;

  $(document).ready(function() {
      $('#pagepiling').pagepiling({
        menu: '#menu',
        anchors: ['Tentang', 'NFF', 'Tema', 'Keluarga'],
        navigation: {
              'textColor': '#f2f2f2',
              'bulletsColor': '#ccc',
              'position': 'right',
              'tooltips': ['Tentang kami', 'Tentang NFF', 'Tema', 'Keluarga NFF']
          }
    });
    });
</script>
{% endblock %}

nff/templates/nff/confirmation_form.html
{% extends 'nff/base.html' %}
{% load staticfiles %}
{% block title %}
Confirmation NFF
{% endblock %}
{% block head %}
<link rel="stylesheet" href="{%static 'nff/css/form.css' %}" />
{% endblock %}
{% block content %}
{% include 'nff/form-template.html' with heading="KONFIRMASI" %}
{% endblock %}

nff/templates/nff/form-template-copy.html
<table>
{% for field in form %}
  <div class="form-group">
    <span class="text-danger small">{{ field.errors }}</span>
      <tr>
        <td><label class="control-label">{{ field.label }}</label></td>
        <td>{{ field }}</td>
      </tr>
  </div>
{% endfor %}
</table>